
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author lumiere
 */
public class form_buku extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_buku.class.getName());
    
    private DefaultTableModel table;
    koneksi_mysql mysqlClient = new koneksi_mysql();
    Connection connect = mysqlClient.buatConnection();
    JasperReport JasReport;
    JasperPrint JasPrint;
    HashMap parameter = new HashMap();
    JasperDesign JasDesign;
    
    /**
     * Creates new form form_buku
     */
    public form_buku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        String[] data={"Kode Buku","Judul Buku","Penerbit","Penulis","Jumlah Buku", "Lokasi Buku"};
        table = new DefaultTableModel(data,0);
        TabelBuku.setModel(table);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KodeBukuValue = new javax.swing.JTextField();
        JudulBukuValue = new javax.swing.JTextField();
        PenerbitValue = new javax.swing.JTextField();
        PenulisValue = new javax.swing.JTextField();
        JumlahBukuValue = new javax.swing.JTextField();
        LokasiBukuValue = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBuku = new javax.swing.JTable();
        BtnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Input Buku");
        jLabel1.setToolTipText("");
        jLabel1.setRequestFocusEnabled(false);

        jLabel2.setText("Kode Buku:");

        jLabel3.setText("Judul Buku:");

        jLabel4.setText("Penerbit:");

        jLabel5.setText("Penulis:");

        jLabel6.setText("Jumlah Buku:");

        jLabel7.setText("Lokasi Buku:");

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(this::BtnSimpanActionPerformed);

        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(this::BtnEditActionPerformed);

        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(this::BtnBatalActionPerformed);

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(this::BtnHapusActionPerformed);

        BtnTutup.setText("Tutup");
        BtnTutup.addActionListener(this::BtnTutupActionPerformed);

        TabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelBuku);

        BtnCetak.setText("Cetak");
        BtnCetak.addActionListener(this::BtnCetakActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LokasiBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JumlahBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PenulisValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PenerbitValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JudulBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KodeBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(BtnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KodeBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JudulBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PenerbitValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PenulisValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JumlahBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LokasiBukuValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnEdit)
                    .addComponent(BtnBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHapus)
                    .addComponent(BtnTutup)
                    .addComponent(BtnCetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        if (KodeBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Buku tidak boleh kosong");
            KodeBukuValue.requestFocus();
            return;
        }
        if (JudulBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Judul Buku tidak boleh kosong");
            JudulBukuValue.requestFocus();
            return;
        }
        if (PenerbitValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Penerbit tidak boleh kosong");
            PenerbitValue.requestFocus();
            return;
        }
        if (PenulisValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Penulis tidak boleh kosong");
            PenulisValue.requestFocus();
            return;
        }
        if (JumlahBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah Buku tidak boleh kosong");
            JumlahBukuValue.requestFocus();
            return;
        }
        if (LokasiBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lokasi Buku tidak boleh kosong");
            LokasiBukuValue.requestFocus();
            return;
        }

        try {
            // ==== CEK DUPLIKASI ====
            String sqlCek = "SELECT COUNT(*) FROM tabel_buku WHERE kode_buku=?";
            PreparedStatement psCek = connect.prepareStatement(sqlCek);
            psCek.setString(1, KodeBukuValue.getText());
            ResultSet rs = psCek.executeQuery();
            rs.next();

            if (rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null,
                    "Kode Buku sudah ada! Gunakan kode lain.");
                KodeBukuValue.requestFocus();
                return;
            }

            // ==== SIMPAN DATA ====
            String sqlInsert = "INSERT INTO tabel_buku VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = connect.prepareStatement(sqlInsert);
            ps.setString(1, KodeBukuValue.getText());
            ps.setString(2, JudulBukuValue.getText());
            ps.setString(3, PenerbitValue.getText());
            ps.setString(4, PenulisValue.getText());
            ps.setString(5, JumlahBukuValue.getText());
            ps.setString(6, LokasiBukuValue.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

            // ==== RESET ====
            KodeBukuValue.setText("");
            JudulBukuValue.setText("");
            PenerbitValue.setText("");
            PenulisValue.setText("");
            JumlahBukuValue.setText("");
            LokasiBukuValue.setText("");
            KodeBukuValue.requestFocus();

            tampil();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        // Bisa diatur sesuai kebutuhan, biasanya kode buku TIDAK diubah saat edit

        // ====== VALIDASI SEDERHANA ======
        if (KodeBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Buku tidak boleh kosong");
            KodeBukuValue.requestFocus();
            return;
        }
        if (JudulBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Judul Buku tidak boleh kosong");
            JudulBukuValue.requestFocus();
            return;
        }
        if (PenerbitValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Penerbit tidak boleh kosong");
            PenerbitValue.requestFocus();
            return;
        }
        if (PenulisValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Penulis tidak boleh kosong");
            PenulisValue.requestFocus();
            return;
        }
        if (JumlahBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah Buku tidak boleh kosong");
            JumlahBukuValue.requestFocus();
            return;
        }
        if (LokasiBukuValue.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lokasi Buku tidak boleh kosong");
            LokasiBukuValue.requestFocus();
            return;
        }

        String kodeBuku   = KodeBukuValue.getText().trim();
        String judul      = JudulBukuValue.getText().trim();
        String penerbit   = PenerbitValue.getText().trim();
        String penulis    = PenulisValue.getText().trim();
        String jumlah     = JumlahBukuValue.getText().trim();
        String lokasi     = LokasiBukuValue.getText().trim();

        try {
            // ====== QUERY UPDATE SEDERHANA ======
            String sql = "UPDATE tabel_buku SET " +
                         "judul_buku = ?, " +
                         "penerbit = ?, " +
                         "penulis = ?, " +
                         "jumlah_buku = ?, " +
                         "lokasi_buku = ? " +
                         "WHERE kode_buku = ?";

            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setString(1, judul);
            ps.setString(2, penerbit);
            ps.setString(3, penulis);
            ps.setString(4, jumlah);
            ps.setString(5, lokasi);
            ps.setString(6, kodeBuku);

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data berhasil diubah");
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Data dengan Kode Buku '" + kodeBuku + "' tidak ditemukan");
            }

            // ====== RESET FORM ======
            KodeBukuValue.setText("");
            JudulBukuValue.setText("");
            PenerbitValue.setText("");
            PenulisValue.setText("");
            JumlahBukuValue.setText("");
            LokasiBukuValue.setText("");
            KodeBukuValue.requestFocus();

            // Refresh tabel
            tampil();

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void TabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBukuMouseClicked
        // TODO add your handling code here:
        int selectedRow = TabelBuku.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TabelBuku.getModel();

        // Ambil nilai dari tabel
        String kodeBuku = model.getValueAt(selectedRow, 0).toString();
        String judulBuku = model.getValueAt(selectedRow, 1).toString();
        String penerbit = model.getValueAt(selectedRow, 2).toString();
        String penulis = model.getValueAt(selectedRow, 3).toString();
        String jumlahBuku = model.getValueAt(selectedRow, 4).toString();
        String lokasiBuku = model.getValueAt(selectedRow, 5).toString();

        // Masukkan ke input field
        KodeBukuValue.setText(kodeBuku);
        JudulBukuValue.setText(judulBuku);
        PenerbitValue.setText(penerbit);
        PenulisValue.setText(penulis);
        JumlahBukuValue.setText(jumlahBuku);
        LokasiBukuValue.setText(lokasiBuku);
    }//GEN-LAST:event_TabelBukuMouseClicked

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        // ====== RESET FORM ======
        KodeBukuValue.setText("");
        JudulBukuValue.setText("");
        PenerbitValue.setText("");
        PenulisValue.setText("");
        JumlahBukuValue.setText("");
        LokasiBukuValue.setText("");
        KodeBukuValue.requestFocus();

        // Refresh tabel
        tampil();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnTutupActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
         String kode = KodeBukuValue.getText().trim();

        if (kode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Buku tidak boleh kosong");
            KodeBukuValue.requestFocus();
            return;
        }

        try {
            String sql = "DELETE FROM tabel_buku WHERE kode_buku = ?";
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setString(1, kode);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data '" + kode + "' berhasil dihapus");

            // Reset input
            KodeBukuValue.setText("");
            JudulBukuValue.setText("");
            PenerbitValue.setText("");
            PenulisValue.setText("");
            JumlahBukuValue.setText("");
            LokasiBukuValue.setText("");
            KodeBukuValue.requestFocus();

            tampil();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        // TODO add your handling code here:
        try {
            File report = new File("./src/report_form_buku.jrxml");
            JasperDesign JasDesign = JRXmlLoader.load(report);
            parameter.clear();
            JasReport = JasperCompileManager.compileReport(JasDesign);
            JasPrint = JasperFillManager.fillReport(JasReport, parameter, connect);
            // Buat instance JasperViewer
            JRViewer viewer = new JRViewer(JasPrint);

            // Buat JFrame baru sebagai container
            JFrame previewFrame = new JFrame("Preview Laporan");
            previewFrame.getContentPane().add(viewer);
            previewFrame.setExtendedState(JFrame.MAXIMIZED_BOTH); // full screen
            previewFrame.setAlwaysOnTop(true); // pastikan di atas
            previewFrame.setLocationRelativeTo(null); // tengah layar
            previewFrame.setVisible(true);
            previewFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }catch(Exception error) {
            JOptionPane.showMessageDialog(null,"Gagal print: " + error.getMessage());
            System.out.println("Gagal print: " + error.getMessage());
        }
    }//GEN-LAST:event_BtnCetakActionPerformed

    private void tampil(){
        try {
            table.setRowCount(0);
            ResultSet result = connect.createStatement().executeQuery("SELECT * FROM tabel_buku");
            while(result.next()){
                String[] data = {result.getString(1),result.getString(2),
                    result.getString(3),result.getString(4),result.getString(5),result.getString(6)};
                table.addRow(data);
            }
        }catch(SQLException error){
            System.out.println("Internal Server Error: " + error.getMessage());
            JOptionPane.showMessageDialog(rootPane, error);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                form_buku dialog = new form_buku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnCetak;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTutup;
    private javax.swing.JTextField JudulBukuValue;
    private javax.swing.JTextField JumlahBukuValue;
    private javax.swing.JTextField KodeBukuValue;
    private javax.swing.JTextField LokasiBukuValue;
    private javax.swing.JTextField PenerbitValue;
    private javax.swing.JTextField PenulisValue;
    private javax.swing.JTable TabelBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
